spring:
  application:
    name: complaints
  datasource:
    url: jdbc:postgresql://localhost:5432/complaints
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080

logging:
  level:
    org.springframework.security: INFO
    org.springframework.test.web.servlet: INFO
    org.flywaydb: INFO
