spring:
  application:
    name: complaints
  datasource:
    url: jdbc:postgresql://localhost:5432/complaints
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 8080
geoip:
  database:
    path: src/main/resources/GeoLite2-Country.mmdb
security:
  jwt:
    secret: your-secret-key-here-minimum-256-bits-long
logging:
  level:
    org.springframework.security: INFO
    org.springframework.test.web.servlet: INFO
    org.flywaydb: INFO
